name: Deploy to EC2 from GitHub project3_todo

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug SSH Variables
      run: |
        echo "Host: ${{ secrets.EC2_HOST }}"
        echo "User: ${{ secrets.EC2_USER }}"
        echo "Key Length: $(echo "${{ secrets.EC2_SSH_KEY }}" | wc -c)"

    - name: Test SSH Connection
      run: |
        ssh -i <(echo "${{ secrets.EC2_SSH_KEY }}") -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH Connection Successful'"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ${{ secrets.EC2_PROJECT_DIR }}
          git pull origin main
          cd client
          npm install
          npm run build
          cd ../server
          npm install
          pm2 restart todo-backend
